const stateTransitionTable =

`
id: ndm
*NDM                d    POPULATION-SAMPLE

 POPULATION-SAMPLE  r    CENTRAL-TENDENCY       
 POPULATION-SAMPLE  l    CENTRAL-VARIATION       
 POPULATION-SAMPLE  u    NDM 

 CENTRAL-VARIATION  l    RANGE 
 CENTRAL-VARIATION  r    PERCENTIL 

 CENTRAL-TENDENCY   l    MODE
 CENTRAL-TENDENCY   d    MEDIAN
 CENTRAL-TENDENCY   r    MEAN

 MODE               u    CENTRAL-TENDENCY
 MEDIAN             u    CENTRAL-TENDENCY
 MEAN               u    CENTRAL-TENDENCY 

 MEAN               d    TRIMMEDMEAN 
 TRIMMEDMEAN        u    MEAN 

 TRIMMEDMEAN        d    OUTLIERS

 OUTLIERS           u    TRIMMEDMEAN

 CENTRAL-TENDENCY   u    POPULATION-SAMPLE	
 CENTRAL-VARIATION  u    POPULATION-SAMPLE	

 RANGE              u    CENTRAL-VARIATION 
 PERCENTIL          u    CENTRAL-VARIATION 

`;



